version: '3.9'

services:
  jb1-backend-watch:
    container_name: jb1-backend-watch
    build:
      context: ./nestjs
    command: bash -c "npm install && npm run start:dev"
    networks:
      - jb1-backend-network
    volumes:
      - ../nestbe:/app
    working_dir: /app

  jb1-watch-nginx:
    container_name: jb1-backend-watch-nginx
    image: nginx:stable
    networks:
      - jb1-backend-network
      - traefik-public
    volumes:
      - ./nginx/jb1-backend-watch.nginx.conf:/etc/nginx/conf.d/default.conf
    working_dir: /etc/nginx/conf.d
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jb1-backend-watch.rule=Host(`jb1-backend-watch.docker.localhost`)"
      - "traefik.http.routers.jb1-backend-watch.entrypoints=http"
      - "traefik.http.routers.jb1-backend-watch-secure.entrypoints=https"
      - "traefik.http.routers.jb1-backend-watch-secure.rule=Host(`jb1-backend-watch.docker.localhost`)"
      - "traefik.http.routers.jb1-backend-watch-secure.tls=true"

  jb1-fe-watch:
    container_name: jb1-fe-watch
    build:
      context: ./nestjs
    command: bash -c "yarn install && yarn start --public-host http://jb1-fe-watch.docker.localhost --host 0.0.0.0 --disable-host-check"
    networks:
      - jb1-fe-network
    volumes:
      - ../angfe:/app
    working_dir: /app

  jb1-fe-nginx:
    container_name: jb1-fe-watch-nginx
    image: nginx:stable
    networks:
      - jb1-fe-network
      - traefik-public
    volumes:
      - ./nginx/jb1-fe-watch.nginx.conf:/etc/nginx/conf.d/default.conf
    working_dir: /etc/nginx/conf.d
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jb1-fe-watch.rule=Host(`jb1-fe-watch.docker.localhost`)"
      - "traefik.http.routers.jb1-fe-watch.entrypoints=http"
      - "traefik.http.routers.jb1-fe-watch-secure.entrypoints=https"
      - "traefik.http.routers.jb1-fe-watch-secure.rule=Host(`jb1-fe-watch.docker.localhost`)"
      - "traefik.http.routers.jb1-fe-watch-secure.tls=true"

networks:
  jb1-backend-network:
    driver: bridge
  jb1-fe-network:
    driver: bridge
  traefik-public:
    external: true
